- uses: actions/setup-python@v4
  with:
    python-version: '3.13'
- name: Install PyTorch with CUDA
run: uv pip install torch==2.9.0+cu130 torchaudio==2.9.0+cu130 torchvision==0.23.0+cu129 --index https://download.pytorch.org/whl/cu130
